version: '3.7'

services:
  traefik:
    image: traefik:2.2
    labels:
      traefik.enable: "false"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml:ro
      - ./traefik.d:/traefik.d:ro
      - ./certs:/certs:ro

  whoami:
    image: containous/whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.tls: "true"

  nginx.sub:
    image: nginx
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx-sub.tls: "true"

    
